# Home-manager module for kyaraben
#
# This module uses the kyaraben CLI for config generation to ensure
# identical behavior between standalone and home-manager usage.
# Config merging (preserving user changes) is handled by the CLI.
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.kyaraben;

  # System and emulator definitions matching the Go code
  # These are used for package installation only; config generation is handled by CLI
  systemEmulators = {
    snes = {
      default = "retroarch:bsnes";
      emulators = {
        "retroarch:bsnes" = pkgs.retroarch.override { cores = with pkgs.libretro; [ bsnes ]; };
      };
    };
    psx = {
      default = "duckstation";
      emulators = {
        duckstation = pkgs.duckstation;
      };
    };
    tic80 = {
      default = "tic80";
      emulators = {
        tic80 = pkgs.tic-80;
      };
    };
  };

  enabledSystems = filterAttrs (name: value: value.enable) cfg.systems;

  # Generate the emulator packages to install
  emulatorPackages = mapAttrsToList (sysName: sysCfg:
    let
      sysInfo = systemEmulators.${sysName};
      emuId = if sysCfg.emulator != null then sysCfg.emulator else sysInfo.default;
    in
    sysInfo.emulators.${emuId}
  ) enabledSystems;

  # Generate kyaraben config.toml content
  kyarabenConfig = ''
    # Generated by kyaraben home-manager module
    # Do not edit directly; changes will be overwritten

    [global]
    user_store = "${cfg.userStore}"

  '' + concatStrings (mapAttrsToList (sysName: sysCfg:
    let
      sysInfo = systemEmulators.${sysName};
      emuId = if sysCfg.emulator != null then sysCfg.emulator else sysInfo.default;
    in ''
    [systems.${sysName}]
    emulator = "${emuId}"

  '') enabledSystems);

in
{
  options.programs.kyaraben = {
    enable = mkEnableOption "kyaraben emulation manager";

    package = mkOption {
      type = types.package;
      default = pkgs.kyaraben or (throw "kyaraben package not available");
      defaultText = literalExpression "pkgs.kyaraben";
      description = "The kyaraben package to use.";
    };

    userStore = mkOption {
      type = types.str;
      default = "~/Emulation";
      example = "/home/user/Games/Emulation";
      description = "Path to the emulation directory containing ROMs, saves, etc.";
    };

    systems = mkOption {
      type = types.attrsOf (types.submodule {
        options = {
          enable = mkEnableOption "this system";
          emulator = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "Emulator to use. If null, uses the default for this system.";
          };
        };
      });
      default = {};
      example = literalExpression ''
        {
          snes.enable = true;
          psx.enable = true;
        }
      '';
      description = "Systems to enable for emulation.";
    };
  };

  config = mkIf cfg.enable {
    # Install kyaraben CLI and emulator packages
    home.packages = [ cfg.package ] ++ emulatorPackages;

    # Write kyaraben config file
    xdg.configFile."kyaraben/config.toml".text = kyarabenConfig;

    # Run kyaraben apply to generate emulator configs
    # This uses the CLI's merge logic which preserves user customizations
    # --config-only skips Nix build (nixpkgs already handles package installation)
    home.activation.kyarabenApply = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      # Only run if kyaraben is available and config exists
      if command -v ${cfg.package}/bin/kyaraben &> /dev/null; then
        $DRY_RUN_CMD ${cfg.package}/bin/kyaraben apply --config-only 2>/dev/null || true
      fi
    '';
  };
}
