package launcher

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/fnune/kyaraben/internal/logging"
)

var log = logging.New("launcher")

type Manager struct {
	profileDir        string
	nixPortableBinary string
}

func NewManager() *Manager {
	homeDir, _ := os.UserHomeDir()
	return &Manager{
		profileDir: filepath.Join(homeDir, ".local", "share", "kyaraben"),
	}
}

func (m *Manager) SetNixPortableBinary(path string) {
	m.nixPortableBinary = path
}

func (m *Manager) ProfileDir() string {
	return m.profileDir
}

func (m *Manager) CurrentLink() string {
	return filepath.Join(m.profileDir, "current")
}

func (m *Manager) Link(storePath string) error {
	log.Info("Linking profile: %s -> %s", m.CurrentLink(), storePath)

	if err := os.MkdirAll(m.profileDir, 0755); err != nil {
		return fmt.Errorf("creating profile directory: %w", err)
	}

	currentLink := m.CurrentLink()

	if _, err := os.Lstat(currentLink); err == nil {
		log.Debug("Removing old symlink: %s", currentLink)
		if err := os.Remove(currentLink); err != nil {
			return fmt.Errorf("removing old symlink: %w", err)
		}
	}

	if err := os.Symlink(storePath, currentLink); err != nil {
		return fmt.Errorf("creating symlink: %w", err)
	}

	if target, err := os.Readlink(currentLink); err == nil {
		log.Info("Created symlink: %s -> %s", currentLink, target)
		if entries, err := os.ReadDir(filepath.Join(target, "bin")); err == nil {
			binaries := make([]string, 0, len(entries))
			for _, e := range entries {
				binaries = append(binaries, e.Name())
			}
			log.Info("Available binaries: %v", binaries)
		}
	}

	return nil
}

func (m *Manager) Unlink() error {
	currentLink := m.CurrentLink()
	if _, err := os.Lstat(currentLink); err == nil {
		return os.Remove(currentLink)
	}
	return nil
}

func (m *Manager) BinDir() string {
	return filepath.Join(m.profileDir, "bin")
}

const wrapperTemplate = `#!/bin/sh
# Generated by kyaraben - do not edit
# Wrapper for {{.BinaryName}} that runs through nix-portable
NP_LOCATION="{{.NpLocation}}" \
exec "{{.NixPortable}}" nix shell "{{.VirtualStorePath}}" -c "{{.BinaryName}}" "$@"
`

type wrapperData struct {
	BinaryName       string
	NixPortable      string
	NpLocation       string
	VirtualStorePath string
}

func (m *Manager) GenerateWrappers() error {
	if m.nixPortableBinary == "" {
		return fmt.Errorf("nix-portable binary path not set")
	}

	binDir := m.BinDir()
	profileBinDir := filepath.Join(m.CurrentLink(), "bin")

	if _, err := os.Stat(profileBinDir); os.IsNotExist(err) {
		log.Info("No bin directory in profile, skipping wrapper generation")
		return nil
	}

	currentTarget, err := os.Readlink(m.CurrentLink())
	if err != nil {
		return fmt.Errorf("reading current link: %w", err)
	}

	virtualStorePath, err := realToVirtualStorePath(currentTarget)
	if err != nil {
		return fmt.Errorf("converting store path: %w", err)
	}

	if err := os.RemoveAll(binDir); err != nil {
		return fmt.Errorf("removing old bin directory: %w", err)
	}

	if err := os.MkdirAll(binDir, 0755); err != nil {
		return fmt.Errorf("creating bin directory: %w", err)
	}

	entries, err := os.ReadDir(profileBinDir)
	if err != nil {
		return fmt.Errorf("reading profile bin directory: %w", err)
	}

	tmpl, err := template.New("wrapper").Parse(wrapperTemplate)
	if err != nil {
		return fmt.Errorf("parsing wrapper template: %w", err)
	}

	npLocation := filepath.Join(m.profileDir, "nix-portable")

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		binaryName := entry.Name()
		wrapperPath := filepath.Join(binDir, binaryName)

		f, err := os.Create(wrapperPath)
		if err != nil {
			return fmt.Errorf("creating wrapper %s: %w", binaryName, err)
		}

		data := wrapperData{
			BinaryName:       binaryName,
			NixPortable:      m.nixPortableBinary,
			NpLocation:       npLocation,
			VirtualStorePath: virtualStorePath,
		}

		if err := tmpl.Execute(f, data); err != nil {
			f.Close()
			return fmt.Errorf("writing wrapper %s: %w", binaryName, err)
		}

		if err := f.Close(); err != nil {
			return fmt.Errorf("closing wrapper %s: %w", binaryName, err)
		}

		if err := os.Chmod(wrapperPath, 0755); err != nil {
			return fmt.Errorf("making wrapper executable %s: %w", binaryName, err)
		}

		log.Debug("Generated wrapper: %s -> %s", wrapperPath, filepath.Join(virtualStorePath, "bin", binaryName))
	}

	log.Info("Generated %d wrapper scripts in %s", len(entries), binDir)
	return nil
}

func realToVirtualStorePath(realPath string) (string, error) {
	const storeMarker = "/nix/store/"
	idx := strings.Index(realPath, storeMarker)
	if idx == -1 {
		return "", fmt.Errorf("path does not contain /nix/store/: %s", realPath)
	}
	return realPath[idx:], nil
}
