version: 2

builds:
  - main: ./cmd/kyaraben
    binary: kyaraben
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    ldflags:
      - -s -w
      - -linkmode external
      - -extldflags '-static'

archives:
  - formats: [binary]
    name_template: "Kyaraben-CLI-linux-amd64"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git-cliff
  args:
    - --config
    - cliff.toml

release:
  draft: true
