package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := findProjectRoot()
	typesFile := filepath.Join(root, "internal/daemon/types.go")
	outputFile := filepath.Join(root, "ui/src/types/generated.ts")

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, typesFile, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing %s: %v\n", typesFile, err)
		os.Exit(1)
	}

	var commandTypes []constValue
	var eventTypes []constValue

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Values) == 0 {
				continue
			}

			for i, name := range valueSpec.Names {
				if i >= len(valueSpec.Values) {
					continue
				}

				lit, ok := valueSpec.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}

				value := strings.Trim(lit.Value, `"`)
				cv := constValue{Name: name.Name, Value: value}

				if strings.HasPrefix(name.Name, "Cmd") {
					commandTypes = append(commandTypes, cv)
				} else if strings.HasPrefix(name.Name, "Event") {
					eventTypes = append(eventTypes, cv)
				}
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/generate-types. DO NOT EDIT.\n\n")

	buf.WriteString("export type DaemonCommandType =\n")
	for i, ct := range commandTypes {
		if i == len(commandTypes)-1 {
			buf.WriteString(fmt.Sprintf("  | '%s'\n", ct.Value))
		} else {
			buf.WriteString(fmt.Sprintf("  | '%s'\n", ct.Value))
		}
	}
	buf.WriteString("\n")

	buf.WriteString("export type EventType =")
	for i, et := range eventTypes {
		if i == 0 {
			buf.WriteString(fmt.Sprintf(" '%s'", et.Value))
		} else {
			buf.WriteString(fmt.Sprintf(" | '%s'", et.Value))
		}
	}
	buf.WriteString("\n\n")

	buf.WriteString("export const DaemonCommands = {\n")
	for _, ct := range commandTypes {
		constName := strings.TrimPrefix(ct.Name, "Cmd")
		buf.WriteString(fmt.Sprintf("  %s: '%s',\n", constName, ct.Value))
	}
	buf.WriteString("} as const\n\n")

	buf.WriteString("export const Events = {\n")
	for _, et := range eventTypes {
		constName := strings.TrimPrefix(et.Name, "Event")
		buf.WriteString(fmt.Sprintf("  %s: '%s',\n", constName, et.Value))
	}
	buf.WriteString("} as const\n")

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "creating output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputFile)
}

type constValue struct {
	Name  string
	Value string
}

func findProjectRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "getting working directory: %v\n", err)
		os.Exit(1)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "could not find project root (no go.mod found)")
			os.Exit(1)
		}
		dir = parent
	}
}
