// Code generated by tygo. DO NOT EDIT.
import type { SystemID, EmulatorID, Manufacturer } from './model.gen'

//////////
// source: protocol.go

export interface SetConfigRequest {
  userStore: string;
  systems: { [key: string]: string[]};
  emulators?: { [key: string]: EmulatorConfRequest};
}
export interface EmulatorConfRequest {
  version?: string;
}
export interface SyncAddDeviceRequest {
  deviceId: string;
  name?: string;
}
export interface SyncRemoveDeviceRequest {
  deviceId: string;
}
export interface ErrorResponse {
  error: string;
}
export interface StatusResponse {
  userStore: string;
  enabledSystems: SystemID[];
  installedEmulators: InstalledEmulator[];
  lastApplied: string;
}
export interface InstalledEmulator {
  id: EmulatorID;
  version: string;
}
/**
 * DoctorResponse uses map[string] because tygo can't generate valid TypeScript
 * for map[EmulatorID] (index signatures don't support union types).
 * The TypeScript type is manually defined as Record<EmulatorID, ProvisionResult[]>.
 */
export type DoctorResponse = { [key: string]: ProvisionResult[]};
export interface ProvisionResult {
  filename: string;
  description: string;
  required: boolean;
  status: string;
  foundPath?: string;
}
export interface ProgressEvent {
  step: string;
  message: string;
  output?: string;
  speed?: string;
}
export interface ApplyResult {
  success: boolean;
  storePath: string;
}
export interface CancelledResponse {
  message: string;
}
export type GetSystemsResponse = SystemWithEmulators[];
export interface SystemWithEmulators {
  id: SystemID;
  name: string;
  description: string;
  manufacturer: Manufacturer;
  label: string;
  emulators: EmulatorRef[];
}
export interface EmulatorRef {
  id: EmulatorID;
  name: string;
  defaultVersion?: string;
  availableVersions?: string[];
  downloadSize?: string;
}
export interface ConfigResponse {
  userStore: string;
  systems: { [key: string]: EmulatorID[]};
  emulators?: { [key: string]: EmulatorConfResponse};
}
export interface EmulatorConfResponse {
  version?: string;
}
export interface SetConfigResponse {
  success: boolean;
}
/**
 * SyncState represents the current state of sync.
 * Constants use the full type name as prefix (SyncState*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const SyncStateDisabled = "disabled";
export const SyncStateSynced = "synced";
export const SyncStateSyncing = "syncing";
export const SyncStateDisconnected = "disconnected";
export const SyncStateConflict = "conflict";
export const SyncStateError = "error";
export type SyncState = typeof SyncStateDisabled | typeof SyncStateSynced | typeof SyncStateSyncing | typeof SyncStateDisconnected | typeof SyncStateConflict | typeof SyncStateError;
export interface SyncStatusResponse {
  enabled: boolean;
  mode?: string;
  running?: boolean;
  deviceId?: string;
  guiURL?: string;
  state?: SyncState;
  devices?: SyncDevice[];
}
export interface SyncDevice {
  id: string;
  name: string;
  connected: boolean;
}
export interface SyncAddDeviceResponse {
  success: boolean;
  deviceId: string;
  name: string;
}
export interface SyncRemoveDeviceResponse {
  success: boolean;
  deviceId: string;
  name: string;
}
export interface UninstallPreviewResponse {
  stateDir: string;
  stateDirExists: boolean;
  desktopFiles: string[];
  iconFiles: string[];
  configFiles: string[];
  preserved: PreservedPaths;
}
export interface PreservedPaths {
  userStore: string;
  configDir: string;
}

//////////
// source: types.go

/**
 * CommandType identifies the type of command.
 * Constants use the full type name as prefix (CommandType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const CommandTypeStatus = "status";
export const CommandTypeDoctor = "doctor";
export const CommandTypeApply = "apply";
export const CommandTypeCancelApply = "cancel_apply";
export const CommandTypeGetSystems = "get_systems";
export const CommandTypeGetConfig = "get_config";
export const CommandTypeSetConfig = "set_config";
export const CommandTypeSyncStatus = "sync_status";
export const CommandTypeSyncAddDevice = "sync_add_device";
export const CommandTypeSyncRemoveDevice = "sync_remove_device";
export const CommandTypeUninstallPreview = "uninstall_preview";
export type CommandType = typeof CommandTypeStatus | typeof CommandTypeDoctor | typeof CommandTypeApply | typeof CommandTypeCancelApply | typeof CommandTypeGetSystems | typeof CommandTypeGetConfig | typeof CommandTypeSetConfig | typeof CommandTypeSyncStatus | typeof CommandTypeSyncAddDevice | typeof CommandTypeSyncRemoveDevice | typeof CommandTypeUninstallPreview;
/**
 * Command represents a command from the UI.
 */
export interface Command {
  type: CommandType;
}
/**
 * SetConfigCommand includes the config data to set.
 */
export interface SetConfigCommand {
  type: CommandType;
  data: SetConfigRequest;
}
/**
 * SyncAddDeviceCommand includes the device to add.
 */
export interface SyncAddDeviceCommand {
  type: CommandType;
  data: SyncAddDeviceRequest;
}
/**
 * SyncRemoveDeviceCommand includes the device to remove.
 */
export interface SyncRemoveDeviceCommand {
  type: CommandType;
  data: SyncRemoveDeviceRequest;
}
/**
 * EventType identifies the type of event.
 * Constants use the full type name as prefix (EventType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const EventTypeReady = "ready";
export const EventTypeResult = "result";
export const EventTypeProgress = "progress";
export const EventTypeError = "error";
export const EventTypeCancelled = "cancelled";
export type EventType = typeof EventTypeReady | typeof EventTypeResult | typeof EventTypeProgress | typeof EventTypeError | typeof EventTypeCancelled;
/**
 * Event represents an event sent to the UI.
 * The Data field contains a typed response struct depending on the command.
 */
export interface Event {
  type: EventType;
  data?: unknown;
}
