// Code generated by tygo. DO NOT EDIT.
import type { SystemID, EmulatorID, FrontendID, Manufacturer } from './model.gen'

//////////
// source: protocol.go

export interface SetConfigRequest {
  userStore: string;
  systems: { [key: string]: string[]};
  emulators?: { [key: string]: EmulatorConfRequest};
  frontends?: { [key: string]: FrontendConfRequest};
}
export interface FrontendConfRequest {
  enabled: boolean;
  version?: string;
}
export interface EmulatorConfRequest {
  version?: string;
}
export interface SyncRemoveDeviceRequest {
  deviceId: string;
}
export interface SyncJoinPrimaryRequest {
  code: string;
  pairingAddr: string;
}
export interface SyncEnableRequest {
  mode: string;
}
export interface ErrorResponse {
  error: string;
}
export interface StatusResponse {
  userStore: string;
  enabledSystems: SystemID[];
  installedEmulators: InstalledEmulator[];
  installedFrontends: InstalledFrontend[];
  symlinks?: SymlinkInfo[];
  lastApplied: string;
  healthWarning?: string;
  kyarabenVersion: string;
  manifestKyarabenVersion?: string;
}
export interface InstalledEmulator {
  id: EmulatorID;
  version: string;
  execLine?: string;
  managedConfigs?: ManagedConfigInfo[];
  iconPath?: string;
  paths?: { [key: string]: EmulatorPaths};
}
export interface ManagedConfigInfo {
  path: string;
  keys: ManagedKeyInfo[];
}
export interface ManagedKeyInfo {
  key: string;
  value: string;
}
export interface SymlinkInfo {
  source: string;
  target: string;
  emulatorId: EmulatorID;
}
export interface EmulatorPaths {
  roms: string;
  bios?: string;
  saves?: string;
  states?: string;
  screenshots?: string;
}
export interface InstalledFrontend {
  id: FrontendID;
  version: string;
}
/**
 * DoctorResponse maps "systemId:emulatorId" to provisions for that system/emulator pair.
 * Uses map[string] because tygo can't generate valid TypeScript for union index types.
 */
export type DoctorResponse = { [key: string]: ProvisionResult[]};
export interface ProvisionResult {
  filename: string;
  kind: string;
  description: string;
  status: string;
  expectedPath?: string;
  foundPath?: string;
  importViaUI?: boolean;
  groupMessage?: string;
  groupRequired: boolean;
  groupSatisfied: boolean;
  groupSize: number /* int */;
  displayName: string;
  verifiedDisplayName?: string;
  instructions?: string;
}
export interface ProgressEvent {
  step: string;
  message: string;
  output?: string;
  buildPhase?: string;
  packageName?: string;
  progressPercent?: number /* int */;
  bytesDownloaded?: number /* int64 */;
  bytesTotal?: number /* int64 */;
  bytesPerSecond?: number /* int64 */;
  logPosition: number /* int64 */;
}
export interface ApplyResult {
  success: boolean;
}
export interface CancelledResponse {
  message: string;
}
export type GetSystemsResponse = SystemWithEmulators[];
export interface SystemWithEmulators {
  id: SystemID;
  name: string;
  description: string;
  manufacturer: Manufacturer;
  label: string;
  defaultEmulatorId: EmulatorID;
  emulators: EmulatorRef[];
}
export interface EmulatorRef {
  id: EmulatorID;
  name: string;
  defaultVersion?: string;
  availableVersions?: string[];
  downloadBytes?: number /* int64 */;
  coreBytes?: number /* int64 */;
  packageName?: string;
}
export interface ConfigResponse {
  userStore: string;
  systems: { [key: string]: EmulatorID[]};
  emulators?: { [key: string]: EmulatorConfResponse};
  frontends?: { [key: string]: FrontendConfResponse};
}
export interface EmulatorConfResponse {
  version?: string;
}
export interface FrontendConfResponse {
  enabled: boolean;
  version?: string;
}
export type GetFrontendsResponse = FrontendRef[];
export interface FrontendRef {
  id: FrontendID;
  name: string;
  defaultVersion?: string;
  availableVersions?: string[];
  downloadBytes?: number /* int64 */;
}
export interface SetConfigResponse {
  success: boolean;
}
/**
 * SyncState represents the current state of sync.
 * Constants use the full type name as prefix (SyncState*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const SyncStateDisabled = "disabled";
export const SyncStateSynced = "synced";
export const SyncStateSyncing = "syncing";
export const SyncStateDisconnected = "disconnected";
export const SyncStateConflict = "conflict";
export const SyncStateError = "error";
export type SyncState = typeof SyncStateDisabled | typeof SyncStateSynced | typeof SyncStateSyncing | typeof SyncStateDisconnected | typeof SyncStateConflict | typeof SyncStateError;
export interface SyncStatusResponse {
  enabled: boolean;
  mode?: string;
  running?: boolean;
  deviceId?: string;
  guiURL?: string;
  state?: SyncState;
  devices?: SyncDevice[];
  folders?: SyncFolder[];
  pairing?: boolean;
  progress?: SyncProgress;
  serviceError?: string;
}
export interface SyncProgress {
  needFiles: number /* int64 */;
  needBytes: number /* int64 */;
  globalBytes: number /* int64 */;
  percent: number /* int */;
}
export interface SyncDevice {
  id: string;
  name: string;
  connected: boolean;
  paused?: boolean;
}
export interface SyncFolder {
  id: string;
  path: string;
  label: string;
  state: string;
  type: string;
  globalSize: number /* int64 */;
  localSize: number /* int64 */;
  needSize: number /* int64 */;
  receiveOnlyChanges: number /* int */;
}
export interface SyncRevertFolderRequest {
  folderId: string;
}
export interface SyncRevertFolderResponse {
  success: boolean;
}
export interface SyncLocalChangesRequest {
  folderId: string;
}
export interface SyncLocalChange {
  action: string;
  type: string;
  path: string;
  modified: string;
  size: number /* int64 */;
}
export interface SyncLocalChangesResponse {
  changes: SyncLocalChange[];
}
export interface SyncPendingResponse {
  pending: boolean;
  totalFiles: number /* int64 */;
  totalBytes: number /* int64 */;
}
export interface SyncRemoveDeviceResponse {
  success: boolean;
  deviceId: string;
  name: string;
}
export interface SyncStartPairingResponse {
  code: string;
}
export interface SyncPairingCompleteResponse {
  success: boolean;
  peerDeviceId: string;
  peerName: string;
}
export interface SyncJoinPrimaryResponse {
  success: boolean;
  peerDeviceId: string;
  peerName: string;
}
export interface SyncPairingProgressEvent {
  message: string;
}
export interface SyncEnableProgressEvent {
  phase: string;
  message: string;
  percent: number /* int */;
}
export interface SyncEnableResponse {
  success: boolean;
}
export interface SyncDiscoveredPrimary {
  hostname: string;
  pairingAddr: string;
}
export interface UninstallPreviewResponse {
  stateDir: string;
  stateDirExists: boolean;
  retroArchCoresDir?: string;
  retroArchCoreFiles?: string[];
  desktopFiles: string[];
  iconFiles: string[];
  configFiles: string[];
  kyarabenFiles: string[];
  syncthingFiles?: string[];
  preserved: PreservedPaths;
}
export interface PreservedPaths {
  userStore: string;
  configDir: string;
}
export interface InstallKyarabenRequest {
  appImagePath?: string;
  sidecarPath?: string;
}
export interface InstallKyarabenResponse {
  success: boolean;
}
export interface InstallStatusResponse {
  installed: boolean;
  appPath?: string;
  desktopPath?: string;
  cliPath?: string;
}
export interface RefreshIconCachesResponse {
  refreshed: string[];
}
export interface UninstallResponse {
  success: boolean;
  removedFiles: string[];
  errors?: string[];
}
export interface PreflightResponse {
  diffs: ConfigFileDiff[];
  filesToBackup: string[];
}
export interface ConfigFileDiff {
  path: string;
  isNewFile: boolean;
  hasChanges: boolean;
  userModified: boolean;
  userChanges?: UserChangeDetail[];
  changes?: ConfigChangeDetail[];
}
export interface UserChangeDetail {
  key: string;
  baselineValue: string;
  currentValue: string;
}
export interface ConfigChangeDetail {
  type: string;
  key: string;
  section?: string;
  oldValue?: string;
  newValue?: string;
}

//////////
// source: types.go

/**
 * CommandType identifies the type of command.
 * Constants use the full type name as prefix (CommandType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const CommandTypeStatus = "status";
export const CommandTypeDoctor = "doctor";
export const CommandTypeApply = "apply";
export const CommandTypeCancelApply = "cancel_apply";
export const CommandTypeGetSystems = "get_systems";
export const CommandTypeGetFrontends = "get_frontends";
export const CommandTypeGetConfig = "get_config";
export const CommandTypeSetConfig = "set_config";
export const CommandTypeSyncStatus = "sync_status";
export const CommandTypeSyncRemoveDevice = "sync_remove_device";
export const CommandTypeSyncStartPairing = "sync_start_pairing";
export const CommandTypeSyncJoinPrimary = "sync_join_primary";
export const CommandTypeSyncCancelPairing = "sync_cancel_pairing";
export const CommandTypeSyncPending = "sync_pending";
export const CommandTypeUninstallPreview = "uninstall_preview";
export const CommandTypeUninstall = "uninstall";
export const CommandTypeInstallKyaraben = "install_kyaraben";
export const CommandTypeInstallStatus = "install_status";
export const CommandTypeRefreshIconCaches = "refresh_icon_caches";
export const CommandTypePreflight = "preflight";
export const CommandTypeSyncEnable = "sync_enable";
export const CommandTypeSyncRevertFolder = "sync_revert_folder";
export const CommandTypeSyncLocalChanges = "sync_local_changes";
export type CommandType = typeof CommandTypeStatus | typeof CommandTypeDoctor | typeof CommandTypeApply | typeof CommandTypeCancelApply | typeof CommandTypeGetSystems | typeof CommandTypeGetFrontends | typeof CommandTypeGetConfig | typeof CommandTypeSetConfig | typeof CommandTypeSyncStatus | typeof CommandTypeSyncRemoveDevice | typeof CommandTypeSyncStartPairing | typeof CommandTypeSyncJoinPrimary | typeof CommandTypeSyncCancelPairing | typeof CommandTypeSyncPending | typeof CommandTypeUninstallPreview | typeof CommandTypeUninstall | typeof CommandTypeInstallKyaraben | typeof CommandTypeInstallStatus | typeof CommandTypeRefreshIconCaches | typeof CommandTypePreflight | typeof CommandTypeSyncEnable | typeof CommandTypeSyncRevertFolder | typeof CommandTypeSyncLocalChanges;
/**
 * Command represents a command from the UI.
 */
export interface Command {
  type: CommandType;
  id?: string;
}
/**
 * SetConfigCommand includes the config data to set.
 */
export interface SetConfigCommand {
  type: CommandType;
  id?: string;
  data: SetConfigRequest;
}
/**
 * SyncRemoveDeviceCommand includes the device to remove.
 */
export interface SyncRemoveDeviceCommand {
  type: CommandType;
  id?: string;
  data: SyncRemoveDeviceRequest;
}
/**
 * SyncJoinPrimaryCommand includes the pairing code and selected primary.
 */
export interface SyncJoinPrimaryCommand {
  type: CommandType;
  id?: string;
  data: SyncJoinPrimaryRequest;
}
/**
 * InstallKyarabenCommand includes the install options.
 */
export interface InstallKyarabenCommand {
  type: CommandType;
  id?: string;
  data: InstallKyarabenRequest;
}
/**
 * SyncEnableCommand includes the sync enable options.
 */
export interface SyncEnableCommand {
  type: CommandType;
  id?: string;
  data: SyncEnableRequest;
}
/**
 * SyncRevertFolderCommand includes the folder to revert.
 */
export interface SyncRevertFolderCommand {
  type: CommandType;
  id?: string;
  data: SyncRevertFolderRequest;
}
/**
 * SyncLocalChangesCommand includes the folder to get local changes for.
 */
export interface SyncLocalChangesCommand {
  type: CommandType;
  id?: string;
  data: SyncLocalChangesRequest;
}
/**
 * EventType identifies the type of event.
 * Constants use the full type name as prefix (EventType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const EventTypeReady = "ready";
export const EventTypeResult = "result";
export const EventTypeProgress = "progress";
export const EventTypeError = "error";
export const EventTypeCancelled = "cancelled";
export type EventType = typeof EventTypeReady | typeof EventTypeResult | typeof EventTypeProgress | typeof EventTypeError | typeof EventTypeCancelled;
/**
 * Event represents an event sent to the UI.
 * The Data field contains a typed response struct depending on the command.
 */
export interface Event {
  type: EventType;
  id?: string;
  data?: unknown;
}
