// Code generated by tygo. DO NOT EDIT.
import type { SystemID, EmulatorID, FrontendID, Manufacturer } from './model.gen'

//////////
// source: protocol.go

export interface SetConfigRequest {
  userStore: string;
  systems: { [key: string]: string[]};
  emulators?: { [key: string]: EmulatorConfRequest};
  frontends?: { [key: string]: FrontendConfRequest};
}
export interface FrontendConfRequest {
  enabled: boolean;
  version?: string;
}
export interface EmulatorConfRequest {
  version?: string;
}
export interface SyncAddDeviceRequest {
  deviceId: string;
  name?: string;
}
export interface SyncRemoveDeviceRequest {
  deviceId: string;
}
export interface ErrorResponse {
  error: string;
}
export interface StatusResponse {
  userStore: string;
  enabledSystems: SystemID[];
  installedEmulators: InstalledEmulator[];
  installedFrontends: InstalledFrontend[];
  lastApplied: string;
  healthWarning?: string;
  kyarabenVersion: string;
  manifestKyarabenVersion?: string;
}
export interface InstalledEmulator {
  id: EmulatorID;
  version: string;
  execLine?: string;
  managedConfigs?: ManagedConfigInfo[];
  iconPath?: string;
  paths?: { [key: string]: EmulatorPaths};
}
export interface ManagedConfigInfo {
  path: string;
  keys: ManagedKeyInfo[];
}
export interface ManagedKeyInfo {
  key: string;
  value: string;
}
export interface EmulatorPaths {
  roms: string;
  bios?: string;
  saves?: string;
  states?: string;
  screenshots?: string;
  opaque?: string;
  opaqueContents?: string;
}
export interface InstalledFrontend {
  id: FrontendID;
  version: string;
}
/**
 * DoctorResponse uses map[string] because tygo can't generate valid TypeScript
 * for map[EmulatorID] (index signatures don't support union types).
 * The TypeScript type is manually defined as Record<EmulatorID, ProvisionResult[]>.
 */
export type DoctorResponse = { [key: string]: ProvisionResult[]};
export interface ProvisionResult {
  filename: string;
  kind: string;
  description: string;
  status: string;
  expectedPath?: string;
  foundPath?: string;
  importViaUI?: boolean;
  groupMessage?: string;
  groupRequired: boolean;
  groupSatisfied: boolean;
  groupSize: number /* int */;
}
export interface ProgressEvent {
  step: string;
  message: string;
  output?: string;
  speed?: string;
}
export interface ApplyResult {
  success: boolean;
  storePath: string;
}
export interface CancelledResponse {
  message: string;
}
export type GetSystemsResponse = SystemWithEmulators[];
export interface SystemWithEmulators {
  id: SystemID;
  name: string;
  description: string;
  manufacturer: Manufacturer;
  label: string;
  defaultEmulatorId: EmulatorID;
  emulators: EmulatorRef[];
}
export interface EmulatorRef {
  id: EmulatorID;
  name: string;
  defaultVersion?: string;
  availableVersions?: string[];
  downloadBytes?: number /* int64 */;
  coreBytes?: number /* int64 */;
  packageName?: string;
}
export interface ConfigResponse {
  userStore: string;
  systems: { [key: string]: EmulatorID[]};
  emulators?: { [key: string]: EmulatorConfResponse};
  frontends?: { [key: string]: FrontendConfResponse};
}
export interface EmulatorConfResponse {
  version?: string;
}
export interface FrontendConfResponse {
  enabled: boolean;
  version?: string;
}
export type GetFrontendsResponse = FrontendRef[];
export interface FrontendRef {
  id: FrontendID;
  name: string;
  defaultVersion?: string;
  availableVersions?: string[];
  downloadBytes?: number /* int64 */;
}
export interface SetConfigResponse {
  success: boolean;
}
/**
 * SyncState represents the current state of sync.
 * Constants use the full type name as prefix (SyncState*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const SyncStateDisabled = "disabled";
export const SyncStateSynced = "synced";
export const SyncStateSyncing = "syncing";
export const SyncStateDisconnected = "disconnected";
export const SyncStateConflict = "conflict";
export const SyncStateError = "error";
export type SyncState = typeof SyncStateDisabled | typeof SyncStateSynced | typeof SyncStateSyncing | typeof SyncStateDisconnected | typeof SyncStateConflict | typeof SyncStateError;
export interface SyncStatusResponse {
  enabled: boolean;
  mode?: string;
  running?: boolean;
  deviceId?: string;
  guiURL?: string;
  state?: SyncState;
  devices?: SyncDevice[];
}
export interface SyncDevice {
  id: string;
  name: string;
  connected: boolean;
}
export interface SyncAddDeviceResponse {
  success: boolean;
  deviceId: string;
  name: string;
}
export interface SyncRemoveDeviceResponse {
  success: boolean;
  deviceId: string;
  name: string;
}
export interface UninstallPreviewResponse {
  stateDir: string;
  stateDirExists: boolean;
  retroArchCoresDir?: string;
  retroArchCoreFiles?: string[];
  desktopFiles: string[];
  iconFiles: string[];
  configFiles: string[];
  kyarabenFiles: string[];
  preserved: PreservedPaths;
}
export interface PreservedPaths {
  userStore: string;
  configDir: string;
}
export interface InstallKyarabenRequest {
  appImagePath?: string;
  sidecarPath?: string;
}
export interface InstallKyarabenResponse {
  success: boolean;
}
export interface InstallStatusResponse {
  installed: boolean;
  appPath?: string;
  desktopPath?: string;
  cliPath?: string;
}
export interface RefreshIconCachesResponse {
  refreshed: string[];
}
export interface UninstallResponse {
  success: boolean;
  removedFiles: string[];
  errors?: string[];
}
export interface PreflightResponse {
  diffs: ConfigFileDiff[];
  filesToBackup: string[];
}
export interface ConfigFileDiff {
  path: string;
  isNewFile: boolean;
  hasChanges: boolean;
  userModified: boolean;
  userChanges?: UserChangeDetail[];
  changes?: ConfigChangeDetail[];
}
export interface UserChangeDetail {
  key: string;
  baselineValue: string;
  currentValue: string;
}
export interface ConfigChangeDetail {
  type: string;
  key: string;
  section?: string;
  oldValue?: string;
  newValue?: string;
}

//////////
// source: types.go

/**
 * CommandType identifies the type of command.
 * Constants use the full type name as prefix (CommandType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const CommandTypeStatus = "status";
export const CommandTypeDoctor = "doctor";
export const CommandTypeApply = "apply";
export const CommandTypeCancelApply = "cancel_apply";
export const CommandTypeGetSystems = "get_systems";
export const CommandTypeGetFrontends = "get_frontends";
export const CommandTypeGetConfig = "get_config";
export const CommandTypeSetConfig = "set_config";
export const CommandTypeSyncStatus = "sync_status";
export const CommandTypeSyncAddDevice = "sync_add_device";
export const CommandTypeSyncRemoveDevice = "sync_remove_device";
export const CommandTypeUninstallPreview = "uninstall_preview";
export const CommandTypeUninstall = "uninstall";
export const CommandTypeInstallKyaraben = "install_kyaraben";
export const CommandTypeInstallStatus = "install_status";
export const CommandTypeRefreshIconCaches = "refresh_icon_caches";
export const CommandTypePreflight = "preflight";
export type CommandType = typeof CommandTypeStatus | typeof CommandTypeDoctor | typeof CommandTypeApply | typeof CommandTypeCancelApply | typeof CommandTypeGetSystems | typeof CommandTypeGetFrontends | typeof CommandTypeGetConfig | typeof CommandTypeSetConfig | typeof CommandTypeSyncStatus | typeof CommandTypeSyncAddDevice | typeof CommandTypeSyncRemoveDevice | typeof CommandTypeUninstallPreview | typeof CommandTypeUninstall | typeof CommandTypeInstallKyaraben | typeof CommandTypeInstallStatus | typeof CommandTypeRefreshIconCaches | typeof CommandTypePreflight;
/**
 * Command represents a command from the UI.
 */
export interface Command {
  type: CommandType;
  id?: string;
}
/**
 * SetConfigCommand includes the config data to set.
 */
export interface SetConfigCommand {
  type: CommandType;
  id?: string;
  data: SetConfigRequest;
}
/**
 * SyncAddDeviceCommand includes the device to add.
 */
export interface SyncAddDeviceCommand {
  type: CommandType;
  id?: string;
  data: SyncAddDeviceRequest;
}
/**
 * SyncRemoveDeviceCommand includes the device to remove.
 */
export interface SyncRemoveDeviceCommand {
  type: CommandType;
  id?: string;
  data: SyncRemoveDeviceRequest;
}
/**
 * InstallKyarabenCommand includes the install options.
 */
export interface InstallKyarabenCommand {
  type: CommandType;
  id?: string;
  data: InstallKyarabenRequest;
}
/**
 * EventType identifies the type of event.
 * Constants use the full type name as prefix (EventType*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const EventTypeReady = "ready";
export const EventTypeResult = "result";
export const EventTypeProgress = "progress";
export const EventTypeError = "error";
export const EventTypeCancelled = "cancelled";
export type EventType = typeof EventTypeReady | typeof EventTypeResult | typeof EventTypeProgress | typeof EventTypeError | typeof EventTypeCancelled;
/**
 * Event represents an event sent to the UI.
 * The Data field contains a typed response struct depending on the command.
 */
export interface Event {
  type: EventType;
  id?: string;
  data?: unknown;
}
