// Code generated by scripts/generate-types. DO NOT EDIT.

export type DaemonCommandType =
  | 'status'
  | 'doctor'
  | 'apply'
  | 'get_systems'
  | 'get_config'
  | 'set_config'
  | 'sync_status'
  | 'sync_add_device'
  | 'sync_remove_device'
  | 'uninstall_preview'

export type EventType = 'ready' | 'result' | 'progress' | 'error'

export const DaemonCommands = {
  Status: 'status',
  Doctor: 'doctor',
  Apply: 'apply',
  GetSystems: 'get_systems',
  GetConfig: 'get_config',
  SetConfig: 'set_config',
  SyncStatus: 'sync_status',
  SyncAddDevice: 'sync_add_device',
  SyncRemoveDevice: 'sync_remove_device',
  UninstallPreview: 'uninstall_preview',
} as const

export const Events = {
  Ready: 'ready',
  Result: 'result',
  Progress: 'progress',
  Error: 'error',
} as const
