// Code generated by tygo. DO NOT EDIT.

//////////
// source: emulator_id.go

/**
 * EmulatorID uniquely identifies an emulator implementation.
 * Format: "emulator" or "emulator:core" for RetroArch cores.
 * Constants use the full type name as prefix (EmulatorID*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
/**
 * EmulatorIDRetroArch is the base RetroArch installation shared by all cores.
 * Used for shared data like the cores directory.
 */
export const EmulatorIDRetroArch = "retroarch";
export const EmulatorIDRetroArchSnes9x = "retroarch:snes9x";
export const EmulatorIDRetroArchBsnes = "retroarch:bsnes";
export const EmulatorIDRetroArchMesen = "retroarch:mesen";
export const EmulatorIDRetroArchGenesisPlusGX = "retroarch:genesis_plus_gx";
export const EmulatorIDRetroArchMupen64Plus = "retroarch:mupen64plus_next";
export const EmulatorIDRetroArchBeetleSaturn = "retroarch:mednafen_saturn";
export const EmulatorIDRetroArchBeetlePCE = "retroarch:mednafen_pce_fast";
export const EmulatorIDRetroArchBeetleNGP = "retroarch:mednafen_ngp";
export const EmulatorIDRetroArchMGBA = "retroarch:mgba";
export const EmulatorIDRetroArchMelonDS = "retroarch:melondsds";
export const EmulatorIDRetroArchCitra = "retroarch:citra";
export const EmulatorIDRetroArchFBNeo = "retroarch:fbneo";
export const EmulatorIDRetroArchStella = "retroarch:stella";
export const EmulatorIDRetroArchVICE = "retroarch:vice_x64sc";
export const EmulatorIDDuckStation = "duckstation";
export const EmulatorIDPCSX2 = "pcsx2";
export const EmulatorIDRPCS3 = "rpcs3";
export const EmulatorIDVita3K = "vita3k";
export const EmulatorIDPPSSPP = "ppsspp";
export const EmulatorIDFlycast = "flycast";
export const EmulatorIDCemu = "cemu";
export const EmulatorIDDolphin = "dolphin";
export const EmulatorIDEden = "eden";
export const EmulatorIDXemu = "xemu";
export const EmulatorIDXeniaEdge = "xenia-edge";
export type EmulatorID = typeof EmulatorIDRetroArch | typeof EmulatorIDRetroArchSnes9x | typeof EmulatorIDRetroArchBsnes | typeof EmulatorIDRetroArchMesen | typeof EmulatorIDRetroArchGenesisPlusGX | typeof EmulatorIDRetroArchMupen64Plus | typeof EmulatorIDRetroArchBeetleSaturn | typeof EmulatorIDRetroArchBeetlePCE | typeof EmulatorIDRetroArchBeetleNGP | typeof EmulatorIDRetroArchMGBA | typeof EmulatorIDRetroArchMelonDS | typeof EmulatorIDRetroArchCitra | typeof EmulatorIDRetroArchFBNeo | typeof EmulatorIDRetroArchStella | typeof EmulatorIDRetroArchVICE | typeof EmulatorIDDuckStation | typeof EmulatorIDPCSX2 | typeof EmulatorIDRPCS3 | typeof EmulatorIDVita3K | typeof EmulatorIDPPSSPP | typeof EmulatorIDFlycast | typeof EmulatorIDCemu | typeof EmulatorIDDolphin | typeof EmulatorIDEden | typeof EmulatorIDXemu | typeof EmulatorIDXeniaEdge;

//////////
// source: frontend_id.go

export type FrontendID = string;
export const FrontendIDESDE: FrontendID = "esde";

//////////
// source: system.go

/**
 * SystemID uniquely identifies a gaming platform.
 * Constants use the full type name as prefix (SystemID*) because tygo's
 * enum_style: union requires the prefix to match the type name exactly.
 */
export const SystemIDNES = "nes";
export const SystemIDSNES = "snes";
export const SystemIDN64 = "n64";
export const SystemIDGB = "gb";
export const SystemIDGBC = "gbc";
export const SystemIDGBA = "gba";
export const SystemIDNDS = "nds";
export const SystemIDN3DS = "n3ds";
export const SystemIDGameCube = "gamecube";
export const SystemIDWii = "wii";
export const SystemIDWiiU = "wiiu";
export const SystemIDSwitch = "switch";
export const SystemIDPSX = "psx";
export const SystemIDPS2 = "ps2";
export const SystemIDPS3 = "ps3";
export const SystemIDPSP = "psp";
export const SystemIDPSVita = "psvita";
export const SystemIDGenesis = "genesis";
export const SystemIDMasterSystem = "mastersystem";
export const SystemIDGameGear = "gamegear";
export const SystemIDSaturn = "saturn";
export const SystemIDDreamcast = "dreamcast";
export const SystemIDPCEngine = "pcengine";
export const SystemIDNGP = "ngp";
export const SystemIDXbox = "xbox";
export const SystemIDXbox360 = "xbox360";
export const SystemIDArcade = "arcade";
export const SystemIDNeoGeo = "neogeo";
export const SystemIDAtari2600 = "atari2600";
export const SystemIDC64 = "c64";
export type SystemID = typeof SystemIDNES | typeof SystemIDSNES | typeof SystemIDN64 | typeof SystemIDGB | typeof SystemIDGBC | typeof SystemIDGBA | typeof SystemIDNDS | typeof SystemIDN3DS | typeof SystemIDGameCube | typeof SystemIDWii | typeof SystemIDWiiU | typeof SystemIDSwitch | typeof SystemIDPSX | typeof SystemIDPS2 | typeof SystemIDPS3 | typeof SystemIDPSP | typeof SystemIDPSVita | typeof SystemIDGenesis | typeof SystemIDMasterSystem | typeof SystemIDGameGear | typeof SystemIDSaturn | typeof SystemIDDreamcast | typeof SystemIDPCEngine | typeof SystemIDNGP | typeof SystemIDXbox | typeof SystemIDXbox360 | typeof SystemIDArcade | typeof SystemIDNeoGeo | typeof SystemIDAtari2600 | typeof SystemIDC64;
/**
 * DisplayType indicates the original display technology for a system.
 */
export const DisplayTypeCRT = "crt";
export const DisplayTypeLCD = "lcd";
export type DisplayType = typeof DisplayTypeCRT | typeof DisplayTypeLCD;
/**
 * Manufacturer represents the company that made a gaming system.
 */
export const ManufacturerNintendo = "Nintendo";
export const ManufacturerSony = "Sony";
export const ManufacturerSega = "Sega";
export const ManufacturerNEC = "NEC";
export const ManufacturerAtari = "Atari";
export const ManufacturerSNK = "SNK";
export const ManufacturerBandai = "Bandai";
export const ManufacturerOther = "Other";
export const ManufacturerMicrosoft = "Microsoft";
export const ManufacturerCommodore = "Commodore";
export type Manufacturer = typeof ManufacturerNintendo | typeof ManufacturerSony | typeof ManufacturerSega | typeof ManufacturerNEC | typeof ManufacturerAtari | typeof ManufacturerSNK | typeof ManufacturerBandai | typeof ManufacturerOther | typeof ManufacturerMicrosoft | typeof ManufacturerCommodore;
/**
 * System represents a gaming platform that can be emulated.
 */
export interface System {
  id: SystemID;
  name: string;
  description: string;
  manufacturer: Manufacturer;
  label: string;
  extensions: string[];
  displayType: DisplayType;
}
