package esde

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/beevik/etree"

	"github.com/fnune/kyaraben/internal/model"
)

type Config struct{}

var settingsTarget = model.ConfigTarget{
	RelPath: "ES-DE/settings/es_settings.xml",
	Format:  model.ConfigFormatRaw,
	BaseDir: model.ConfigBaseDirHome,
}

var systemsTarget = model.ConfigTarget{
	RelPath: "ES-DE/custom_systems/es_systems.xml",
	Format:  model.ConfigFormatRaw,
	BaseDir: model.ConfigBaseDirHome,
}

func (c *Config) Generate(ctx model.FrontendContext) ([]model.ConfigPatch, error) {
	patches := make([]model.ConfigPatch, 0, 2)

	settingsPatch, err := c.generateSettings(ctx)
	if err != nil {
		return nil, fmt.Errorf("generating settings: %w", err)
	}
	patches = append(patches, settingsPatch)

	systemsPatch, err := c.generateSystems(ctx)
	if err != nil {
		return nil, fmt.Errorf("generating systems: %w", err)
	}
	patches = append(patches, systemsPatch)

	return patches, nil
}

func (c *Config) generateSettings(ctx model.FrontendContext) (model.ConfigPatch, error) {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0"`)

	romDirElem := doc.CreateElement("string")
	romDirElem.CreateAttr("name", "ROMDirectory")
	romDirElem.CreateAttr("value", ctx.Store.RomsDir())

	doc.Indent(2)
	content, err := doc.WriteToString()
	if err != nil {
		return model.ConfigPatch{}, fmt.Errorf("serializing settings XML: %w", err)
	}

	return model.ConfigPatch{
		Target: settingsTarget,
		Entries: []model.ConfigEntry{
			{Value: content},
		},
	}, nil
}

func (c *Config) generateSystems(ctx model.FrontendContext) (model.ConfigPatch, error) {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0"`)
	doc.CreateComment(" ES-DE custom systems - generated by Kyaraben ")

	systemList := doc.CreateElement("systemList")

	sortedSystems := make([]model.SystemID, len(ctx.EnabledSystems))
	copy(sortedSystems, ctx.EnabledSystems)
	sort.Slice(sortedSystems, func(i, j int) bool {
		return string(sortedSystems[i]) < string(sortedSystems[j])
	})

	for _, sysID := range sortedSystems {
		mapping, ok := GetSystemMapping(sysID)
		if !ok {
			continue
		}

		sys, err := ctx.GetSystem(sysID)
		if err != nil {
			continue
		}

		emulators := ctx.SystemEmulators[sysID]
		if len(emulators) == 0 {
			continue
		}

		systemElem := systemList.CreateElement("system")
		systemElem.CreateElement("name").SetText(mapping.Name)
		systemElem.CreateElement("fullname").SetText(mapping.FullName)
		systemElem.CreateElement("path").SetText(filepath.Join("%ROMPATH%", string(sysID)))
		systemElem.CreateElement("extension").SetText(formatExtensions(sys.Extensions))
		systemElem.CreateElement("command").SetText(c.buildCommand(ctx, emulators[0], sysID))
		systemElem.CreateElement("platform").SetText(mapping.Platform)
	}

	doc.Indent(2)
	content, err := doc.WriteToString()
	if err != nil {
		return model.ConfigPatch{}, fmt.Errorf("serializing systems XML: %w", err)
	}

	return model.ConfigPatch{
		Target: systemsTarget,
		Entries: []model.ConfigEntry{
			{Value: content},
		},
	}, nil
}

func (c *Config) buildCommand(ctx model.FrontendContext, emuID model.EmulatorID, sysID model.SystemID) string {
	emu, err := ctx.GetEmulator(emuID)
	if err != nil {
		return ""
	}

	var launchArgs []string
	if gen := ctx.GetConfigGenerator(emuID); gen != nil {
		if provider, ok := gen.(model.LaunchArgsProvider); ok {
			launchArgs = provider.LaunchArgs(ctx.Store)
		}
	}

	return emu.Launcher.RomCommand(model.RomLaunchOptions{
		BinaryPath: filepath.Join(ctx.BinDir, emu.Launcher.Binary),
		Fullscreen: true,
		SavesDir:   ctx.Store.SystemSavesDir(sysID),
		LaunchArgs: launchArgs,
	})
}

func formatExtensions(exts []string) string {
	var result []string
	for _, ext := range exts {
		result = append(result, ext)
		result = append(result, strings.ToUpper(ext))
	}
	return strings.Join(result, " ")
}
