package esde

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/beevik/etree"

	"github.com/fnune/kyaraben/internal/model"
)

type Config struct{}

var settingsTarget = model.ConfigTarget{
	RelPath: "ES-DE/settings/es_settings.xml",
	Format:  model.ConfigFormatRaw,
	BaseDir: model.ConfigBaseDirHome,
}

var systemsTarget = model.ConfigTarget{
	RelPath: "ES-DE/custom_systems/es_systems.xml",
	Format:  model.ConfigFormatRaw,
	BaseDir: model.ConfigBaseDirHome,
}

var findRulesTarget = model.ConfigTarget{
	RelPath: "ES-DE/custom_systems/es_find_rules.xml",
	Format:  model.ConfigFormatRaw,
	BaseDir: model.ConfigBaseDirHome,
}

func (c *Config) Generate(ctx model.FrontendContext) ([]model.ConfigPatch, error) {
	patches := make([]model.ConfigPatch, 0, 3)

	settingsPatch, err := c.generateSettings(ctx)
	if err != nil {
		return nil, fmt.Errorf("generating settings: %w", err)
	}
	patches = append(patches, settingsPatch)

	systemsPatch, err := c.generateSystems(ctx)
	if err != nil {
		return nil, fmt.Errorf("generating systems: %w", err)
	}
	patches = append(patches, systemsPatch)

	findRulesPatch, err := c.generateFindRules(ctx)
	if err != nil {
		return nil, fmt.Errorf("generating find rules: %w", err)
	}
	patches = append(patches, findRulesPatch)

	return patches, nil
}

func (c *Config) generateSettings(ctx model.FrontendContext) (model.ConfigPatch, error) {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0"`)

	romDirElem := doc.CreateElement("string")
	romDirElem.CreateAttr("name", "ROMDirectory")
	romDirElem.CreateAttr("value", ctx.Store.RomsDir())

	doc.Indent(2)
	content, err := doc.WriteToString()
	if err != nil {
		return model.ConfigPatch{}, fmt.Errorf("serializing settings XML: %w", err)
	}

	return model.ConfigPatch{
		Target: settingsTarget,
		Entries: []model.ConfigEntry{
			{Value: content},
		},
	}, nil
}

func (c *Config) generateSystems(ctx model.FrontendContext) (model.ConfigPatch, error) {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0"`)
	doc.CreateComment(" ES-DE custom systems - generated by Kyaraben ")

	systemList := doc.CreateElement("systemList")

	sortedSystems := make([]model.SystemID, len(ctx.EnabledSystems))
	copy(sortedSystems, ctx.EnabledSystems)
	sort.Slice(sortedSystems, func(i, j int) bool {
		return string(sortedSystems[i]) < string(sortedSystems[j])
	})

	for _, sysID := range sortedSystems {
		mapping, ok := GetSystemMapping(sysID)
		if !ok {
			continue
		}

		sys, err := ctx.GetSystem(sysID)
		if err != nil {
			continue
		}

		emulators := ctx.SystemEmulators[sysID]
		if len(emulators) == 0 {
			continue
		}

		systemElem := systemList.CreateElement("system")
		systemElem.CreateElement("name").SetText(mapping.Name)
		systemElem.CreateElement("fullname").SetText(mapping.FullName)
		systemElem.CreateElement("path").SetText(filepath.Join("%ROMPATH%", mapping.Name))
		systemElem.CreateElement("extension").SetText(formatExtensions(sys.Extensions))
		systemElem.CreateElement("command").SetText(c.buildCommand(ctx, emulators[0]))
		systemElem.CreateElement("platform").SetText(mapping.Platform)
	}

	doc.Indent(2)
	content, err := doc.WriteToString()
	if err != nil {
		return model.ConfigPatch{}, fmt.Errorf("serializing systems XML: %w", err)
	}

	return model.ConfigPatch{
		Target: systemsTarget,
		Entries: []model.ConfigEntry{
			{Value: content},
		},
	}, nil
}

func (c *Config) generateFindRules(ctx model.FrontendContext) (model.ConfigPatch, error) {
	doc := etree.NewDocument()
	doc.CreateProcInst("xml", `version="1.0"`)
	doc.CreateComment(" ES-DE find rules - generated by Kyaraben ")

	ruleList := doc.CreateElement("ruleList")

	emulatorElem := ruleList.CreateElement("emulator")
	emulatorElem.CreateAttr("name", "kyaraben")

	ruleElem := emulatorElem.CreateElement("rule")
	ruleElem.CreateAttr("type", "staticpath")

	entryElem := ruleElem.CreateElement("entry")
	entryElem.SetText(ctx.BinDir)

	doc.Indent(2)
	content, err := doc.WriteToString()
	if err != nil {
		return model.ConfigPatch{}, fmt.Errorf("serializing find rules XML: %w", err)
	}

	return model.ConfigPatch{
		Target: findRulesTarget,
		Entries: []model.ConfigEntry{
			{Value: content},
		},
	}, nil
}

func (c *Config) buildCommand(ctx model.FrontendContext, emuID model.EmulatorID) string {
	emu, err := ctx.GetEmulator(emuID)
	if err != nil {
		return ""
	}

	binary := filepath.Join(ctx.BinDir, emu.Launcher.Binary)

	if isRetroArchCore(emuID) {
		coreName := retroArchCoreName(emuID)
		return fmt.Sprintf("%s -L %s %%ROM%%", binary, coreName)
	}

	return fmt.Sprintf("%s %%ROM%%", binary)
}

func formatExtensions(exts []string) string {
	var result []string
	for _, ext := range exts {
		result = append(result, ext)
		result = append(result, strings.ToUpper(ext))
	}
	return strings.Join(result, " ")
}

func isRetroArchCore(emuID model.EmulatorID) bool {
	switch emuID {
	case model.EmulatorIDRetroArchBsnes,
		model.EmulatorIDRetroArchMesen,
		model.EmulatorIDRetroArchGenesisPlusGX,
		model.EmulatorIDRetroArchMupen64Plus,
		model.EmulatorIDRetroArchBeetleSaturn:
		return true
	}
	return false
}

func retroArchCoreName(emuID model.EmulatorID) string {
	switch emuID {
	case model.EmulatorIDRetroArchBsnes:
		return "bsnes_libretro"
	case model.EmulatorIDRetroArchMesen:
		return "mesen_libretro"
	case model.EmulatorIDRetroArchGenesisPlusGX:
		return "genesis_plus_gx_libretro"
	case model.EmulatorIDRetroArchMupen64Plus:
		return "mupen64plus_next_libretro"
	case model.EmulatorIDRetroArchBeetleSaturn:
		return "mednafen_saturn_libretro"
	}
	return ""
}
