// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export const LogLevelDebug = "debug";
export const LogLevelInfo = "info";
export const LogLevelWarn = "warn";
export const LogLevelError = "error";
export type LogLevel = typeof LogLevelDebug | typeof LogLevelInfo | typeof LogLevelWarn | typeof LogLevelError;
export interface LogEntry {
  level: LogLevel;
  component?: string;
  message: string;
  timestamp: string;
  attrs?: { [key: string]: any};
}
